### ISSUE TITLE
用 module.exports 导出模拟数据报错

### ISSUE THREAD

**Issue by Ttou** [xuxihai123/vue-cli-plugin-mock#1]
用 export default 没问题

**Comment by haixuxu** [comment]
这个原因是@vue/babel-preset-app 默认使用的useBuiltins为usage导致.
[https://github.com/webpack/webpack/issues/4039#issuecomment-419284940](https://github.com/webpack/webpack/issues/4039#issuecomment-419284940)

fix 653366ac4095f713414ea9fae3cf84784688116a
