### ISSUE TITLE
使用fs读取假数据文件时报错Error: Can't resolve 'fs'

### ISSUE THREAD

**Issue by tossers** [xuxihai123/vue-cli-plugin-mock#12]
报错如下：

![image](https://user-images.githubusercontent.com/20487985/86144110-d3d08c00-bb27-11ea-8258-79eb364e9869.png)

版本信息：

 "vue-cli-plugin-mock": "^1.0.0",

@vue/cli 4.2.3

![image](https://user-images.githubusercontent.com/20487985/86144388-32960580-bb28-11ea-93ad-aaaff96f093a.png)

**Comment by haixuxu** [comment]
use webpack loader or require.context
```js
// use es6 import with json loader
import userList from './userList.json';

// use require.context
// aaa.json,test.json
const requireAll = (context) => context.keys().map(context);
const context = require.context('./', true, /\.json$/);

requireAll(context).forEach((item) => {
  // get json obj
  console.log(item);
});
```
