### ISSUE TITLE
How to mock HTTP status code?

### ISSUE THREAD

**Issue by yasinshaw** [xuxihai123/vue-cli-plugin-mock#2]
先赞一个，感谢作者提供这个插件！
我想mock HTTP状态码，目前有这个功能吗？看测试用例没有看到呢。
比如我希望在一个错误用户名密码的case，mock出的结果是HTTP code为403之类的。
除此以外，也希望可以在某些时候可以mock HTTP Headers。
感谢~

---
Firstly, thank you for developing so great plugin!
Does this plugin have the function that mock HTTP status code now? I haven't found the test cases about this.
For example, there is a case that I give a incorrect username and password, I want to mock a response which HTTP code is 403.
Further more, I also want I can set the HTTP Headers sometimes.
It will be cool if this plugin has above functions.

Thanks again~

**Comment by haixuxu** [comment]
@yasinshaw  可以参考[express 文档](http://expressjs.com/zh-cn/api.html#res.json) 
headers也可以在上面的文档里面找到,下面是设置403状态码的mock

---
here, resolve it . You can refer to official documents.[express api](http://expressjs.com/zh-cn/api.html#res.json)
```
const mockMap={
   'DELETE /api/user/:id': (req, res) => {
      console.log('---->', req.body);
      console.log('---->', req.params.id);
      res.status(403).json({error: 'message'});
    },
}
```

[config headers](http://expressjs.com/zh-cn/api.html#res.set)

**Comment by yasinshaw** [comment]
Thanks!
