### ISSUE TITLE
建议约定大于配置

### ISSUE THREAD

**Issue by sanwv** [xuxihai123/vue-cli-plugin-mock#3]
现在需要配置配置entry，建议给entry设置默认值`./mock/index.js`

**Comment by haixuxu** [comment]
@sanwv support entry default value 42da4853e63dcb4bc8207e93a446ba6542e3c785

**Comment by sanwv** [comment]
感谢改进。

> mock 数据入口，默认为./mock/index.js.该文件会根据项目的 babel 配置编译

有点不太理解为什么要通过babel编译：
1. entry文件运行在dev server的node环境下，各种语法都支持了。
2. 在实践中引入mockjs使用`Mock.Random.dataImage`报`require is not a function`，好像引入了复杂度？

**Comment by sanwv** [comment]
![image](https://user-images.githubusercontent.com/4526812/54649728-5de91280-4ae6-11e9-8d75-60f3fbdd9e2d.png)

**Comment by haixuxu** [comment]
@sanwv 
1.为支持es6语法。src目录里面用import export模块，考虑mock引用src下es6模块的情况
2. 这是mockjs的issue 
https://github.com/nuysoft/Mock/issues/111
https://github.com/nuysoft/Mock/issues/222

webpack打包后代码：
https://github.com/nuysoft/Mock/blob/refactoring/dist/mock.js#L1476
```
var Canvas = module.require('canvas')
canvas = new Canvas()
```
webpack的module上没有这require这个方法，这是node的api
