### ISSUE TITLE
如何模拟网络延时

### ISSUE THREAD

**Issue by sanwv** [xuxihai123/vue-cli-plugin-mock#5]
开发的时候需要api延时，以便模拟网络状况不佳场景。可否考虑增加此功能呢？或者请教下有其他最佳实践吗？

谢谢

**Comment by haixuxu** [comment]
1. 可以在回调里面使用setTimeout函数来延迟响应请求。

2. 模拟网络延时可以在chrome 的开发工具里面来限定网络模式，可以配置3G, 2G 等。


sanwv <notifications@github.com> 于 2019年4月5日周五 22:36写道：
