### ISSUE TITLE
如何禁用mock

### ISSUE THREAD

**Issue by sanwv** [xuxihai123/vue-cli-plugin-mock#6]
请教下，需要禁用mock，在`vue.config.js`里面配置`devServer.proxy`转发到项目后端服务器，与后端联调呢

**Comment by xuxihai123** [comment]
把配置去掉不行吗？还要啥配置。。

sanwv <notifications@github.com> 于 2019年4月9日周二 16:55写道：

**Comment by haixuxu** [comment]
mock 中间件在代理中间件前面。不存在mock 就到代理了
所以可以:
1. 可以套一层entry.不用的时候注释掉，这样更容易控制某一个接口的联调，不影响其他的mock 
2. 或者用另一个空的entry来切换禁用掉所有
3. 根据插件配置项控制是否启用

**Comment by haixuxu** [comment]
support disable option 9f98c69cce60fea5cfd900b9d1d5c5b8823997ec
`
module.exports = {
    pluginOptions: {
        mock: { disable: true }
    }
}
`

**Comment by sanwv** [comment]
> mock 中间件在代理中间件前面。不存在mock 就到代理了
> 所以可以:
> 
> 1. 可以套一层entry.不用的时候注释掉，这样更容易控制某一个接口的联调，不影响其他的mock
> 2. 或者用另一个空的entry来切换禁用掉所有
> 3. 根据插件配置项控制是否启用

不太理解第一项，你会如何套一层entry单独联调一个接口而不影响其他mock？

**Comment by haixuxu** [comment]
> > mock 中间件在代理中间件前面。不存在mock 就到代理了
> > 所以可以:
> > 
> > 1. 可以套一层entry.不用的时候注释掉，这样更容易控制某一个接口的联调，不影响其他的mock
> > 2. 或者用另一个空的entry来切换禁用掉所有
> > 3. 根据插件配置项控制是否启用
> 
> 不太理解第一项，你会如何套一层entry单独联调一个接口而不影响其他mock？

`
let userApi = require('user');

const mockMap = {
  // 'POST /api/v1/users': userApi.create,
  // 'PUT /api/v1/users/:id': userApi.update,
  // 'DELETE /api/v1/users/:id': userApi.delete,
  // 'GET /api/v1/users': userApi.getAll,
};
module.exports = mockMap;
`

**Comment by sanwv** [comment]
🤗
